### PR TITLE
fix: fix `MissingPluginException` for opening file when add to app

### PR DESCRIPTION
**Pull request by joker-fu**

### CODE REVIEW

**Comment by javaherisaber** [comment]
@joker-fu 
Could you please add some description and more context to your pull request?
I'm not sure how to reproduce your issue

**Comment by joker-fu** [comment]
open_filex throw MissingPluginException when I add a flutter module to app. (via flutter boost)

**Comment by dawid-niedzwiecki** [comment]
Great!

**Comment by javaherisaber** [comment]
@joker-fu 
A [new version](https://pub.dev/packages/open_filex/versions/4.5.0) including your fix is now published to the pub.dev
Sorry for the delay, I've been busy last year and couldn't make it
Thanks for your efforts on this PR

**Pull request closed without merging**
