### PR TITLE
fix: remove REQUEST_INSTALL_PACKAGES permission.

### PR DESCRIPTION
**Pull request by thebeast1**
I comment the function than request the REQUEST_INSTALL_PACKAGES permission because when i was trying to deploy on google paly, my app was rejected because of this permission.

### CODE REVIEW

**Comment by thebeast1** [comment]
remove dangerous permission `REQUEST_INSTALL_PACKAGES` in Android in OpenFilePlugin.java

**Comment by rpekarek-tc** [comment]
We are having this issue as well, even though the permission has been removed it from the manifest. It seems as if Google is doing a plain text search. Maybe it should be deleted altogether instead of commented out?

**Comment by marcellocamara** [comment]
I'm facing this same problema too. I was using open_file, and changed to this one, cleaned the setup and Google Play is still recusing my app update due to this permission.

The curious detail is that I've read the entiry merged_manifests, and there is no such permission. Why the hell Google Play still rejecting?

**Comment by RafaRuiz** [comment]
Same thing here, no matter `open_file` with 

```
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" tools:node="remove"/>
```

or `open_filex`

or any fork with no mention in the code about the permission, we're getting it rejected too.

**Comment by thebeast1** [comment]
That's the same thing that happened to us too, and got rejected.
Then we submitted an appeal, but that process took too long,
We removed the permission even from commented code from the package (in case they are doing a plain search into reversed code).
Then "because our case was a new app" we created a new project on the play console, and it got approved within a couple of hours, and all updates after went smoothly as well.

**Comment by marcellocamara** [comment]
The appeal seems to resolve it.

In my case, I sent an appeal, and they rejected for another reason now (this is very much strange).

`Your offer does not clearly and accurately describe the terms of your subscription, including the cost, frequency of billing cycle, and whether a subscription is required to use the app.`

My app is with the same subscription area for more than 1 year 😄

**Review by javaherisaber — APPROVED** [review]
@thebeast1 
I've been busy lately that's why I couldn't take a look at your PR
Thanks for noticing the issue and the fix

**Comment by javaherisaber** [comment]
@thebeast1 @rpekarek-tc @marcellocamara @RafaRuiz 
A new version for this issue is published now at [open_filex](https://pub.dev/packages/open_filex)

**Pull request merged**
