### PR TITLE
Linux and Macos file opening fix

### PR DESCRIPTION
**Pull request by prateekmedia**
This PR reduces the code from two files to 4 lines  and also fixes the error in linux and mac on opening of files with special characters.

More info from on crazecoder/open_file#156:
> This removes the ability to use `system` to open files. Instead we use `Process.runSync`.
> 
> Quoting the [manpage for `system`](https://man.archlinux.org/man/system.3):
> 
> > Any user input that is employed as part of command should be carefully sanitized,
> > to ensure that unexpected shell commands or command options are not executed.
> 
> AFAICT only spaces are replaced with `\ ` right now. This is not enough, and invoking the `system` function is also completely unnecessary. Creating a new process directly is both simpler and better. This option was introduced in #127, however only on linux and not as the default. This is not sufficient.
> 
> Without this PR, running the following in an unsandboxed flutter app on linux would open `gnome-calculator` (if installed, but you can place any command in there that will be executed):
> 
> ```dart
>   OpenFile.open(";gnome-calculator");
> ```
> 
> I haven't tested this on macOS but it _should_ work there similarly to linux.

### CODE REVIEW

**Comment by prateekmedia** [comment]
@javaherisaber can you merge this please?

**Comment by prateekmedia** [comment]
It may have some merge conflicts as it is not my code, but from my side it is verified to be legitimate and working.

**Comment by javaherisaber** [comment]
@prateekmedia 
See [this ](https://github.com/crazecoder/open_file/pull/156#issuecomment-1872929579) comment related to your PR

**Comment by lexxxel** [comment]
@javaherisaber any updates or is your fork dead?

**Pull request closed without merging**
