### PR TITLE
JCenter to mavenCentral

### PR DESCRIPTION
**Pull request by BetterB0y**
currently, the jcenter is down, and it's better if we can fix this on open_filex.
thank you

### CODE REVIEW

**Comment by BetterB0y** [comment]
@javaherisaber can you look into it?

**Comment by javaherisaber** [comment]
@BetterB0y 
According to (this)[https://blog.gradle.org/jcenter-shutdown] document, JCenter will be `read-only` indefinitely 
> JFrog has decided to keep JCenter as a read-only repository indefinitely. New package and versions are no longer accepted on JCenter. All Bintray services have been shutdown.

Have you seen any issues while building the library?

**Comment by BetterB0y** [comment]
Yes. Yesterday the whole repo was 403 error and unreachable.
Here is stack thread
https://stackoverflow.com/questions/74258160/is-jcenter-down-permanently-31-oct

**Comment by BetterB0y** [comment]
Today is also 403. Check by yourself.

https://jcenter.bintray.com

**Comment by javaherisaber** [comment]
@BetterB0y 
I just checked again and it's not throwing 403 for me, (I also cleaned my cache and retried)
Anyway I checked, replacing `JCenter` with `MavenCentral` satisfies the dependencies
So I can merge your change and make it future proof

Thanks for noticing and the PR

**Pull request merged**
